### ISSUE TITLE
Rule with class and conditions doesn't work

### ISSUE THREAD

**Issue by davidgpgr94** [stalniy/casl#430]
First at all, sorry if I forgot something.

**Describe the bug**
When I define rules using a class name in typescript, in that rules where there are some condition always return false.

**To Reproduce**

I have these classes `User` and `Post`
```
enum Role {
  ADMIN = 'admin',
  USER = 'user'
}

class User {
  id: number;
  login: string;
  role: Role;
}

class Post {
  title: string;
  text: string;
  authrorId: number;
}
```
I define the rules in a static class method called `createForUser` as follow:
```
enum Action {
  MANAGE = 'manage',
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete'
}

type Subjects = typeof Post | typeof User | Post | User | 'all';
type AppAbility = Ability<[Action, Subjects}>;

class CaslAbilityFactory {
  static createForUser(user: User) {
    cosnt { can, cannot, build } = new AbilityBuilder<AppAbility>(Ability as AbilityClass<AppAbility>);
    if (user.role === Role.ADMIN) {
      can(Action.MANAGE, 'all');
    } else {
      can(Action.READ, Post);
      cannot(Action.DELETE, Post);
    }
    can(Action.UPDATE, Post, { authorId: user.id });
    return build();
  }
}
```

When I check the ability of READ a post, with a user with Role USER, it works as expected. The problem is when I check to update a post as follow:

```
const user: User = new User();
user.id = 1;
user.login = 'user01';
user.role = Role.USER;

const post: Post = new Post();
post.title = "Dummy post";
post.text = "Something interesting";
post.authorId = user.id;

const ability = CaslAbilityFactory.createForUser(user);
console.log(ability.can(Action.READ, Post));  // ---> Prints true and expected true.
console.log(ability.can(Action.UPDATE, post));  // ---> Prints false, but expected true
```

But if we add `'Post'` to the type `Subjects` and change `Post` for `'Post'` as following:
```
type Subjects = typeof Post | typeof User | Post | User | 'Post' | 'all';

class CaslAbilityFactory {
  ...
  
  can(Action.UPDATE, 'Post', { authorId: user.id });
  ...
  return build();
}

console.log(ability.can(Action.READ, Post));  // ---> Prints true and expected true.
console.log(ability.can(Action.UPDATE, post));  // ---> Now prints true and expected true
```

I tried too of downgrade `@casl/ability` to version 4.1.6 and the first code (using `Post` in the rule specification) works as expected.

**Interactive example**
Here is a link to the interactive example in codesandobx. https://codesandbox.io/s/casl-bug-3txfo?file=/src/index.ts

**CASL Version**
`@casl/ability` - 5.1.1

**Environment**:
`node` - 12.18.4
`typescript` - 4.1.3

**Comment by stalniy** [comment]
Hi,

thanks for the issue! It’s actually strange because there is a test for this behavior - https://github.com/stalniy/casl/blob/master/packages/casl-ability/spec/ability.spec.js#L99

but I’ll check your example a bit later

**Comment by stalniy** [comment]
Ah I see. The test doesn’t take into account class instance check...

**Comment by davidgpgr94** [comment]
That is! When there is no "instance conditions" (don't know how name it exactly 😅)  it works fine.

**Comment by stalniy** [comment]
Ok. The documentation is a bit wrong on this subject. What you need to do is to provide a custom `detectSubjectType`:

```ts

static createForUser(user: User) {
  // all code except return
  return build({
    detectSubjecType: type => type === “all” ? type : type!.constructor
}

```

**Comment by davidgpgr94** [comment]
To be able to do it (without typescript errors) I had to add `// @ts-ignore` because `detectSubjectType` expects a string, but `type.constructor` returns a Function

```typescript
static createForUser(user: User) {
  // all code except return
  return build({
    // @ts-ignore
    detectSubjecType: type => type!.constructor
  })
}
```

**Comment by stalniy** [comment]
Good catch! Will fix it tomorrow! Thanks!

**Comment by stalniy** [comment]
I also plan to add instrumentation to casl a bit later so it’s easier to understand what’s wrong

**Comment by stalniy** [comment]
fixed in 5.1.2

**Comment by davidgpgr94** [comment]
Just only a comment. In the example that I said, I still have to add `//@ts-ignore` in the `build({ ... })`. Don't know if that is as expected or not. In any case, thanks for fixing it so quickly.

**Comment by stalniy** [comment]
Ts issue should be fixed properly. The issue with constructor is that it’s not strongly typed in TS. That’s why it complains. 

`object.constructor` is `Function` in ts. For details https://github.com/Microsoft/TypeScript/issues/3841 . So, either use type casting with `as` or `@ts-ignore`

**Comment by stalniy** [comment]
Or strongly type your constructors

**Comment by ThomasEddie** [comment]
``` 
Policie.gaurd.ts

type PolicyHandlerCallback = (ability: AppAbility) => boolean;
export interface IPolicyHandler {
  handle(ability: AppAbility): boolean;
}
export type PolicyHandler = IPolicyHandler | PolicyHandlerCallback;
export const CHECK_POLICIES_KEY = "check_policy";
@Injectable()
export class PoliciesGuard implements CanActivate {
  constructor(
    private reflector: Reflector,
    private caslAbilityFactory: CaslAbilityFactory,
  ) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const policyHandlers =
      this.reflector.get<PolicyHandler[]>(
        CHECK_POLICIES_KEY,
        context.getHandler(),
      ) || [];

    const { user } = context.switchToHttp().getRequest();
    const ability = this.caslAbilityFactory.createForUser(user);

    return policyHandlers.every((handler) =>
      this.execPolicyHandler(handler, ability),
    );
  }

  private execPolicyHandler(handler: PolicyHandler, ability: AppAbility) {
    if (typeof handler === "function") {
      return handler(ability);
    }
    return handler.handle(ability);
  }
}

=========================
Policie.decorator.ts

export const CheckPolicies = (...handlers: PolicyHandler[]) =>
  SetMetadata(CHECK_POLICIES_KEY, handlers);
========================
Blog.Entities.ts
@Entity({ name: "blog" })
export class BlogEntity extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;
  @Column()
  description: string;

  @Column({ type: "boolean", default: true })
  isPublished: boolean;

  @CreateDateColumn()
  createdDate: Date;

  @UpdateDateColumn()
  updatedDate: Date;
}
======================
casl.ability.facory.ts

export type Entities = typeof UserEntity | typeof BlogEntity | "all";
export type AppAbility = Ability<[Action, Entities]>;
@Injectable()
export class CaslAbilityFactory {
  createForUser(user: UpdateUserDto) {
    const { can, cannot, build, rules } = new AbilityBuilder<
      Ability<[Action, Entities]>
    >(Ability as AbilityClass<AppAbility>);

    if (user.role === UserRole.ADMIN) {
      can(Action.Manage, "all");
      cannot(Action.Delete, BlogEntity, { isPublished:true });
    }

    return build();
  }
}
```
when i set ``` cannot(Action.Delete, BlogEntity, { isPublished:true });  my blog that include isPushlished:true or false ``` still cannot delete

**Comment by stalniy** [comment]
@ThomasEddie you didn’t specified `detectSubjectType` function:

```ts

static createForUser(user: User) {
  // all code except return
  return build({
    detectSubjecType: type => type!.constructor as any
  })
}

```

**Comment by ThomasEddie** [comment]
@stalniy  it still doesn't work sir

```
In my Blog Controller
@Delete("delete/:id")
@UseGuards(JwtAuthGuard, PoliciesGuard)
@CheckPolicies((ability: AppAbility) => ability.cannot(Action.Delete, BlogEntity))
remove(@Param("id") id: number): Observable<any> {
    return from(this.blogService.remove(id));
 }


========
My PolicieGuard

@Injectable()
export class PoliciesGuard implements CanActivate {
  constructor(
    private reflector: Reflector,
    private caslAbilityFactory: CaslAbilityFactory,
  ) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const policyHandlers =
      this.reflector.get<PolicyHandler[]>(
        CHECK_POLICIES_KEY,
        context.getHandler(),
      ) || [];

    const { user } = context.switchToHttp().getRequest();
    const ability = CaslAbilityFactory.createForUser(user);

    return policyHandlers.every((handler) =>
      this.execPolicyHandler(handler, ability),
    );
  }

  private execPolicyHandler(handler: PolicyHandler, ability: AppAbility) {
    if (typeof handler === "function") {
      return handler(ability);
    }
    return handler.handle(ability);
  }
}
```

why blog with published true still can delete

**Comment by davidgpgr94** [comment]
You need to send a instance of BlogEntity.
What you have is like you were doing `ability.cannot(Action.Delete, BlogEntity)`, but you need do `ability.cannot(Action.Delete, blogEntityInstance)` for the `cannot(Action.Delete, BlogEntity, { isPublished: true });` rule to be executed.
You will need to make some changes in your guard to send to the handler that instance.
I hope I have explained myself well.

**Comment by ThomasEddie** [comment]
@davidgpgr94  what is blogEntityInstance sir can u example for.me

**Comment by davidgpgr94** [comment]
`const blogEntityInstance = new BlogEntity();` or `const blogEntityInstance = blogRepository.findOne(blogId);`

**Comment by ThomasEddie** [comment]
@davidgpgr94  How about subjects should I use BlogEntity or blogEntity Instance ? Sir

**Comment by davidgpgr94** [comment]
Casl subjects still be as you have it. Check how I handle this here:
https://github.com/davidgpgr94/nestjs-blog-api/blob/master/src/posts/controllers/posts.controller.ts#L81
https://github.com/davidgpgr94/nestjs-blog-api/blob/master/src/casl/casl-ability.factory.ts#L13

**Comment by ThomasEddie** [comment]
@davidgpgr94 I appreciate ur help sir thank you alot

**Comment by Gleb-Gaiduk** [comment]
Hello there!
Have similar problem discussed above.
Can't find a solution.
Kindly ask you to help with it.
Here is a link to the description:
https://stackoverflow.com/questions/70584146/nest-js-authorization-with-casl-doesnt-work-as-expected
